networks:
  smartwallet:
    name: smartwallet

services:
  mysql:
    image: mysql:8.0
    container_name: smartwallet-mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartwallet
      MYSQL_USER: smartwallet
      MYSQL_PASSWORD: smartwallet
    volumes:
      - /opt/docker/smartwallet/mysql:/var/lib/mysql:delegated
    networks:
      - smartwallet
    ports:
      - "8952:3306"
    restart: unless-stopped
