version: '3.7'

networks:
  smart-wallet-network:
    name: smart-wallet-network

services:
  mysql:
    image: mysql:8.0
    container_name: smart-wallet-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart-walletdb
      MYSQL_USER: smart-wallet
      MYSQL_PASSWORD: smart-wallet
    volumes:
      - /opt/docker/smart-walletdb/mysql:/var/lib/mysql:delegated
    networks:
      - smart-wallet-network
    ports:
      - "8952:3306"
    restart: unless-stopped
