version: "3.8"

networks:
  smart-wallet-network:
    name: smart-wallet-network
    external: true

services:
  php:
    container_name: smart-wallet-php
    env_file:
      - .env
    networks:
      - smart-wallet-network
    restart: unless-stopped

  caddy:
    container_name: smart-wallet-caddy
    depends_on:
      - php
    ports:
      - "8950:80"
    networks:
      - smart-wallet-network
    restart: unless-stopped
