networks:
  smartwallet:
    name: smartwallet
    external: true

services:
  php:
    container_name: smartwallet-php
    env_file:
      - .env
    networks:
      - smartwallet
    restart: unless-stopped

  caddy:
    container_name: smartwallet-caddy
    depends_on:
      - php
    ports:
      - "8950:80"
    networks:
      - smartwallet
    restart: unless-stopped
